[build]
  command = "npx tailwindcss -i ./input.css -o ./bin/style.css"
  publish = "bin"
  base = "src"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200